apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/TBThomas56/auth_sample_service
    targetRevision: HEAD
    path: charts/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
