postgres:
  auth:
    database: "keycloak"
    password: "postgres"
  initContainers:
    - name: fix-permissions
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          chown -R 999:999 /var/lib/postgresql
          find /var/lib/postgresql -type d -exec chmod 750 {} \;
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
      volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql

keycloak:
  postgres:
    enabled: false
  features:
    enabled:
      - token-exchange
      - admin-fine-grained-authz:v1
  database:
    host: "infra-postgres"
    name: "keycloak"
    existingSecret: "infra-postgres"
    secretKeys:
      passwordKey: "postgres-password"
      usernameKey: "username"
  extraInitContainers:
    - name: wait-for-postgres
      image: busybox:1.36
      command:
        - sh
        - -c
        - until nc -z infra-postgres 5432; do echo "waiting for postgres"; sleep 2; done
